name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - uses: actions/javascript-action@v1
        with: 
          milliseconds: 1000
